name:        toolbox
version:     0.1.2.0
github:      "bi-functor/toolbox"
license:     BSD3
author:      "Melanie Brown"
maintainer:  "brown.m@pm.me"
copyright:   "(c) 2021 Melanie Brown"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/bi-functor/toolbox#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - template-haskell
  - time

library:
  source-dirs: src
  ghc-options: -Wall -haddock
